from django.contrib import admin
from calculator.models import *

admin.site.register(user)
admin.site.register(stuff_table)
admin.site.register(hero_table)
admin.site.register(talent_table)
admin.site.register(skin_table)
admin.site.register(altar_table)
admin.site.register(jewel_type_table)
admin.site.register(jewel_level_table)
admin.site.register(egg_table)
admin.site.register(egg_equipped_table)
admin.site.register(dragon_table)
admin.site.register(runes_table)
admin.site.register(reforge_table)
admin.site.register(refine_table)
admin.site.register(dmg_calc_table)
admin.site.register(medals_table)
admin.site.register(relics_table)
admin.site.register(weapon_skins_table)
admin.site.register(promo_code)
admin.site.register(Token)
admin.site.register(UserQueue)