version: '3.9'

services:
  db:
    image: postgres:14
    container_name: archero-db
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust  # Add this line
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - internal

  web:
    image: archero:v1.7.2
    restart: always
    container_name: archero-web
    command: gunicorn app.wsgi:application --bind=0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - internal
      - web


volumes:
  db:

networks:
  internal:
  web:
    external: false