version: '3.9'

services:
  db:
    image: postgres
    container_name: archero-db
    restart: always
    volumes: 
      - path_local_db_data_store:/var/lib/postgresql/data
    environment:
      # - POSTGRES_NAME=##
      # - POSTGRES_DB=##
      # - POSTGRES_USER=##
      # - POSTGRES_PASSWORD=##
      # - POSTGRES_HOST=##
      # - POSTGRES_HOST_AUTH_METHOD=##
      # - ALLOWED_HOSTS = ##
    networks:
      - internal

  web:
    image: archero
    restart: always
    container_name: archero-web
    command: gunicorn app.wsgi:application --bind=0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - internal
      - web


volumes:
  db:

networks:
  internal:
  web:
    external: false