name: deploy-image

on:
  workflow_dispatch:
    inputs:
      image_version:
        description: 'Version of the image'
        required: true
      static_version:
        description: 'Static version'
        required: true
  push:
    branches:
      - feature/*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "Creating .env file"
          echo "STATIC_VERSION=\"2.0.0b\"" >> .env
          echo "${{ secrets.ENV_FILE_CONTENT }}" >> .env

      - name: Move .env file in /web-project/.env
        run: mv .env web-project/.env

      - name: Log in to Docker registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
            cd web-project/
            docker build -t "${{ secrets.DOCKER_REGISTRY }}/archero:v2.0.0b" .

      - name: Push Docker image
        run: |
            cd web-project/
            docker push "${{ secrets.DOCKER_REGISTRY }}/archero:v2.0.0b"