name: deploy-image

on:
  workflow_dispatch:
    inputs:
      image_version:
        description: 'Version of the image'
        required: true
      static_version:
        description: 'Static version'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "Creating .env file"
          echo "ENV_FILE_CONTENT=${{ secrets.ENV_FILE_CONTENT }}" >> .env

      - name: Debug current directory
        run: ls -la

      - name: Move .env file in /web-project/.env
        run: mv .env web-project/.env

      - name: Log in to Docker registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login "${{ secrets.DOCKER_REGISTRY }}" -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t "${{ secrets.DOCKER_REGISTRY }}/archero:v${{ github.event.inputs.image_version }}" .

      - name: Push Docker image
        run: docker push "${{ secrets.DOCKER_REGISTRY }}/archero:v${{ github.event.inputs.image_version }}"