name: deploy-image

on:
  workflow_dispatch:
    inputs:
      image_version:
        description: 'Version of the image'
        required: true
      static_version:
        description: 'Static version'
        required: true
  push:
    branches:
      - feature/*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "Creating .env file"
          echo "STATIC_VERSION=\"2.0.0b\"" >> .env
          echo "ENV_FILE_CONTENT=${{ secrets.ENV_FILE_CONTENT }}" >> .env

      - name: Debug current directory
        run: ls -la

      - name: Debug web-project directory (if it exists)
        run: ls -la web-project || echo "Directory web-project does not exist"

      - name: Move .env file in /web-project/.env
        run: mv .env web-project/.env

      - name: Log in to Docker registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login "${{ secrets.DOCKER_REGISTRY }}" -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t "${{ secrets.DOCKER_REGISTRY }}/archero:v2.0.0b" .

      - name: Push Docker image
        run: docker push "${{ secrets.DOCKER_REGISTRY }}/archero:v2.0.0b"